name = "kmnd-api"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kmnd-db"
database_id = "a2ed6698-edf4-45d7-97f3-f177d7544030"

[[triggers]]
crons = ["0 * * * *"]
